### ISSUE TITLE
Is it normal behavior for the container to stop once the sync is complete?

### ISSUE THREAD

**Issue by cirrusflyer** [maxkratz/docker_offlineimap#1]
Is it normal behavior for the container to stop once the sync is complete?

**Comment by maxkratz** [comment]
@cirrusflyer Yes, this is normal behavior. The container does not run as a continuous service, it rather is a "one-time run" application created for the periodic use triggered by, for example, `cron`.

**Comment by maxkratz** [comment]
I will close this issue now.
