### ISSUE TITLE
Add date-based tags on Dockerhub

### ISSUE THREAD

**Issue by aigoncharov** [maxkratz/docker_offlineimap#9]
Hi there,
Would you consider adding a release tag on Dockerhub? Using `:latest` is never safe as things might break unexpectedly.
Thanks!

**Comment by maxkratz** [comment]
Hi @aigoncharov, thank you for your input. I agree that only providing `latest` isn't the best idea.
However, I struggle to find a way to come up with tags. Some ideas would be:
- use a custom tag, e.g., `2024-06-11`, for the date I publish a new container image
- use the exact version of `offlineimap` from the container's image

What do you think about it?

Did you encounter a breaking change when using my container so far?

**Comment by aigoncharov** [comment]
> Hi @aigoncharov, thank you for your input. I agree that only providing `latest` isn't the best idea. However, I struggle to find a way to come up with tags. Some ideas would be:
> 
>     * use a custom tag, e.g., `2024-06-11`, for the date I publish a new container image
> 
>     * use the exact version of `offlineimap` from the container's image
> 
> 
> What do you think about it?
> 
> Did you encounter a breaking change when using my container so far?

Nope. The container is great! I guess my mind just never stops searching for things that could go wrong :)
Were I given a choice, I'd go with a date.

**Comment by maxkratz** [comment]
> Nope. The container is great! I guess my mind just never stops searching for things that could go wrong :) Were I given a choice, I'd go with a date.

Agreed! I will rename this issue and come up with a date-based tagging solution.

**Comment by maxkratz** [comment]
@aigoncharov I've adapted my GitHub Actions CI configuration to build and release tagged versions on Dockerhub. The build of todays run can be found here: [v2024.06.15](https://hub.docker.com/layers/maxkratz/offlineimap/v2024.06.15/images/sha256-784b19962b1d437b92a3354525e912c4df73785c1d7355ef17323bd595221934?context=explore)

`latest` still points to the latest release so no existing configuration should break.
